[package]
name = "urska_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
reagent ={ git = "https://github.com/VakeDomen/Reagent.git", branch = "main" }
serde_json = "1.0.140"
tokio = {version ="1.45.1", features = ["rt-multi-thread"]}
